// <auto-generated />
using BanAdmin;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BanAdmin.Migrations
{
    [DbContext(typeof(BanAdminDBContext))]
    [Migration("20210919174623_Initial_SimpleLogin")]
    partial class Initial_SimpleLogin
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.10");

            modelBuilder.Entity("BanAdmin.BanAdminDBContext+LoginDetails", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Username");

                    b.ToTable("Login");
                });
#pragma warning restore 612, 618
        }
    }
}
